#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  1 10:17:08 2022

@author: sjcet
"""

import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)
print("matrix multiplication")
print(np.dot(x,y))
print("trancepose of matrix")
print(np.transpose(x))
print(np.transpose(y))